use crate::ast::{Module, Node, Stmt, Expr, Visitor};
use crate::token::Token;
use crate::ty::{Type, TypeKind};
use crate::ast::Modifier;
use std::collections::HashMap;
use std::fmt::Write;

/// Types inferred by the type checker, keyed by AST node address.
///
/// The type checker and the code generator both borrow the *same* `Module`, so these
/// addresses stay valid and let codegen re-use inferred information (most importantly
/// closure parameter types, which are not written anywhere in the AST).
pub type ExprTypes = HashMap<*const Expr, Type>;

/// The CppCodeGenerator traverses the AST and produces C++ source code.
pub struct CppCodeGenerator {
    output: String,
    indent_level: usize,
    expr_types: ExprTypes,
    /// True while generating the body of a `main` that was declared as returning `void`,
    /// so bare `return;` statements can be lowered to `return 0;`.
    in_synthesised_int_main: bool,
}

impl CppCodeGenerator {
    /// Creates a new C++ code generator.
    pub fn new() -> Self {
        Self {
            output: String::new(),
            indent_level: 0,
            expr_types: ExprTypes::new(),
            in_synthesised_int_main: false,
        }
    }

    /// Creates a code generator that can consult the types inferred by the type checker.
    pub fn with_types(expr_types: ExprTypes) -> Self {
        Self {
            expr_types,
            ..Self::new()
        }
    }

    /// Generate C++ code from a Module AST.
    pub fn generate(&mut self, module: &Module) -> String {
        // C++ header includes.
        self.writeln("#include <iostream>");
        self.writeln("#include <vector>");
        self.writeln("#include <string>");
        self.writeln("#include <sstream>");
        self.writeln("#include <cstdlib>");
        self.writeln("#include <functional>");
        self.writeln("#include <tuple>");
        self.writeln("#include \"std.hpp\"");
        self.writeln("");

        // Cardamom does not require a function to be declared before it is used, but C++
        // does, so emit prototypes for every top-level function up front.
        self.write_function_prototypes(module);

        module.accept(self);

        // C++ programs need an entry point even when the source module has no `main`.
        if !Self::has_main(module) {
            self.writeln("int main()");
            self.writeln("{");
            self.indent_level += 1;
            self.writeln("return 0;");
            self.indent_level -= 1;
            self.writeln("}");
        }

        self.output.clone()
    }

    fn has_main(module: &Module) -> bool {
        module.statements.iter().any(|stmt| {
            matches!(&**stmt, Stmt::Function { name, .. } if name.lexeme == "main")
        })
    }

    fn write_function_prototypes(&mut self, module: &Module) {
        let mut wrote_any = false;
        for stmt in &module.statements {
            if let Stmt::Function { name, params, return_type, modifiers, generics, .. } = &**stmt {
                // `main` is special-cased below, extern builtins are emitted in full, and
                // generic functions have no single concrete signature to declare.
                if name.lexeme == "main"
                    || modifiers.contains(&Modifier::Extern)
                    || !generics.is_empty()
                {
                    continue;
                }
                let ret_type = self.translate_type(return_type);
                let param_str = self.translate_params(params);
                self.writeln(&format!("{} {}({});", ret_type, name.lexeme, param_str));
                wrote_any = true;
            }
        }
        if wrote_any {
            self.writeln("");
        }
    }

    /// Renders a parameter list (`int a, std::string b`) for a function or method.
    fn translate_params(&self, params: &[Box<Stmt>]) -> String {
        let mut param_str = String::new();
        for param in params.iter() {
            if let Stmt::Variable { name, type_, .. } = &**param {
                if !param_str.is_empty() {
                    param_str.push_str(", ");
                }
                write!(&mut param_str, "{} {}", self.translate_type(type_), name.lexeme).unwrap();
            }
        }
        param_str
    }

    /// Returns a string of indentation based on the current indent level.
    fn indent(&self) -> String {
        "    ".repeat(self.indent_level)
    }

    /// Writes a line with the current indent.
    fn writeln(&mut self, line: &str) {
        let _ = writeln!(self.output, "{}{}", self.indent(), line);
    }

    /// A helper to temporarily capture output generated by a closure.
    fn capture_output<F: FnOnce(&mut Self)>(&mut self, f: F) -> String {
        let original = self.output.clone();
        self.output.clear();
        f(self);
        let captured = self.output.clone();
        self.output = original;
        captured
    }

    /// Translates a source language Type into a corresponding C++ type.
    fn translate_type(&self, ty: &Type) -> String {
        match &ty.kind {
            TypeKind::Int => "int".to_string(),
            TypeKind::Float => "float".to_string(),
            TypeKind::String => "std::string".to_string(),
            TypeKind::Void => "void".to_string(),
            TypeKind::User(name) => name.clone(), // assume user types become class names
            TypeKind::Array(inner, depth) => {
                let mut inner_type = self.translate_type(inner);
                for _ in 0..*depth {
                    inner_type = format!("std::vector<{}>", inner_type);
                }
                inner_type
            }
            // Function values (closures and function pointers) become `std::function`, so
            // they can hold both plain functions and capturing lambdas.
            TypeKind::Function(params, ret) => {
                let params_str = params
                    .iter()
                    .map(|p| self.translate_type(p))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("std::function<{}({})>", self.translate_type(ret), params_str)
            }
            TypeKind::Pointer(inner) => format!("{}*", self.translate_type(inner)),
            // `&T` is a borrow that the type checker already treats as interchangeable with
            // `T`, so it is lowered to a by-value parameter; `#T` is the mutable form and
            // becomes a real C++ reference.
            TypeKind::Reference(inner) => self.translate_type(inner),
            TypeKind::MutRef(inner) => format!("{}&", self.translate_type(inner)),
            TypeKind::Tuple(elements) => {
                let elements_str = elements
                    .iter()
                    .map(|e| self.translate_type(e))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("std::tuple<{}>", elements_str)
            }
            TypeKind::GenericInstance(name, args) => {
                let args_str = args
                    .iter()
                    .map(|a| self.translate_type(a))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("{}<{}>", name, args_str)
            }
            TypeKind::GenericParam(name) => name.clone(),
        }
    }

    /// Check if a function is a built-in function and generate its C++ code.
    /// Returns true if the function is a built-in and was generated.
    fn builtin_function(&mut self, name: &Token, _params: &[Box<Stmt>], _return_type: &Type) -> bool {
        if name.lexeme == "print" {
            self.writeln("void print(std::string s) {");
            self.indent_level += 1;
            self.writeln("std::cout << s;");
            self.indent_level -= 1;
            self.writeln("}");
            return true;
        }
        if name.lexeme == "println" {
            self.writeln("void println(std::string s) {");
            self.indent_level += 1;
            self.writeln("std::cout << s << std::endl;");
            self.indent_level -= 1;
            self.writeln("}");
            return true;
        }
        if name.lexeme == "input" {
            self.writeln("std::string input() {");
            self.indent_level += 1;
            self.writeln("std::string line;");
            self.writeln("std::getline(std::cin, line);");
            self.writeln("return line;");
            self.indent_level -= 1;
            self.writeln("}");
            return true;
        }
        if name.lexeme == "toInt" {
            self.writeln("int toInt(std::string s) {");
            self.indent_level += 1;
            self.writeln("return std::stoi(s);");
            self.indent_level -= 1;
            self.writeln("}");
            return true;
        }
        if name.lexeme == "toFloat" {
            self.writeln("float toFloat(std::string s) {");
            self.indent_level += 1;
            self.writeln("return std::stof(s);");
            self.indent_level -= 1;
            self.writeln("}");
            return true;
        }
        if name.lexeme == "toString" {
            self.writeln("std::string toString(int s) {");
            self.indent_level += 1;
            self.writeln("return std::to_string(s);");
            self.indent_level -= 1;
            self.writeln("}");
            return true;
        }
        if name.lexeme == "fromASCII" {
            self.writeln("std::string fromASCII(int ascii) {");
            self.indent_level += 1;
            self.writeln("return std::string(1, static_cast<char>(ascii));");
            self.indent_level -= 1;
            self.writeln("}");
            return true;
        }
        if name.lexeme == "len" {
            self.writeln("int len(std::string s) {");
            self.indent_level += 1;
            self.writeln("return s.size();");
            self.indent_level -= 1;
            self.writeln("}");
            return true;
        }
        if name.lexeme == "charAt" {
            self.writeln("std::string charAt(std::string s, int i) {");
            self.indent_level += 1;
            self.writeln("return std::string(1, s.at(i));");
            self.indent_level -= 1;
            self.writeln("}");
            return true;
        }
        if name.lexeme == "charCodeAt" {
            self.writeln("int charCodeAt(std::string s, int i) {");
            self.indent_level += 1;
            self.writeln("return static_cast<unsigned char>(s.at(i));");
            self.indent_level -= 1;
            self.writeln("}");
            return true;
        }
        false
    }

    fn write_call_arguments(&mut self, arguments: &[Box<Expr>]) {
        for (i, arg) in arguments.iter().enumerate() {
            arg.accept(self);
            if i < arguments.len() - 1 {
                self.output.push_str(", ");
            }
        }
    }

    fn visit_member_call(&mut self, object: &Expr, name: &Token, arguments: &[Box<Expr>]) {
        match name.lexeme.as_str() {
            "push" => {
                object.accept(self);
                self.output.push_str(".push_back(");
                self.write_call_arguments(arguments);
                self.output.push(')');
            }
            "pop" => {
                object.accept(self);
                self.output.push_str(".pop_back()");
            }
            "len" => {
                // `.size()` is unsigned; cast so it can be mixed with `int` arithmetic and
                // comparisons without signed/unsigned surprises.
                self.output.push_str("static_cast<int>(");
                object.accept(self);
                self.output.push_str(".size())");
            }
            "charAt" => {
                self.output.push_str("std::string(1, ");
                object.accept(self);
                self.output.push_str(".at(");
                self.write_call_arguments(arguments);
                self.output.push_str("))");
            }
            "charCodeAt" => {
                self.output.push_str("static_cast<int>(static_cast<unsigned char>(");
                object.accept(self);
                self.output.push_str(".at(");
                self.write_call_arguments(arguments);
                self.output.push_str(")))");
            }
            _ => {
                object.accept(self);
                self.output.push('.');
                self.output.push_str(&name.lexeme);
                self.output.push('(');
                self.write_call_arguments(arguments);
                self.output.push(')');
            }
        }
    }
}

/// Implement the Visitor trait to generate C++ code.
/// Each method converts the corresponding AST node into its C++ representation.
impl Visitor for CppCodeGenerator {
    // Module
    fn visit_module(&mut self, module: &Module) {
        for stmt in &module.statements {
            stmt.accept(self);
        }
    }

    // Statements
    fn visit_block(&mut self, stmt: &Stmt) {
        if let Stmt::Block { statements } = stmt {
            self.writeln("{");
            self.indent_level += 1;
            for s in statements {
                s.accept(self);
            }
            self.indent_level -= 1;
            self.writeln("}");
        }
    }

    fn visit_expression(&mut self, stmt: &Stmt) {
        if let Stmt::Expression { expression } = stmt {
            self.output.push_str(&self.indent());
            expression.accept(self);
            self.output.push_str(";");
            self.output.push('\n');
        }
    }

    fn visit_if(&mut self, stmt: &Stmt) {
        if let Stmt::If { condition, then_branch, else_branch } = stmt {
            self.output.push_str(&self.indent());
            self.output.push_str("if (");
            condition.accept(self);
            self.output.push_str(") ");
            match &**then_branch {
                Stmt::Block { .. } => then_branch.accept(self),
                _ => {
                    self.output.push('\n');
                    self.indent_level += 1;
                    then_branch.accept(self);
                    self.indent_level -= 1;
                }
            }
            if let Some(else_branch) = else_branch {
                self.output.push_str(&self.indent());
                self.output.push_str("else ");
                match &**else_branch {
                    Stmt::Block { .. } => else_branch.accept(self),
                    _ => {
                        self.output.push('\n');
                        self.indent_level += 1;
                        else_branch.accept(self);
                        self.indent_level -= 1;
                    }
                }
            }
        }
    }

    fn visit_while(&mut self, stmt: &Stmt) {
        if let Stmt::While { condition, body } = stmt {
            self.output.push_str(&self.indent());
            self.output.push_str("while (");
            condition.accept(self);
            self.output.push_str(") ");
            body.accept(self);
        }
    }

    fn visit_for(&mut self, stmt: &Stmt) {
        if let Stmt::For { initialiser, condition, increment, body } = stmt {
            self.output.push_str(&self.indent());
            self.output.push_str("for (");
            if let Some(init) = initialiser {
                let init_code = self.capture_output(|gen| { init.accept(gen); });
                self.output.push_str(&init_code);
            } else {
                self.output.push_str("; ");
            }
            if let Some(cond) = condition {
                let cond_code = self.capture_output(|gen| { cond.accept(gen); });
                self.output.push_str(&cond_code);
            }
            self.output.push_str("; ");
            if let Some(inc) = increment {
                let inc_code = self.capture_output(|gen| { inc.accept(gen); });
                self.output.push_str(&inc_code);
            }
            self.output.push_str(") ");
            body.accept(self);
        }
    }

    fn visit_return(&mut self, stmt: &Stmt) {
        if let Stmt::Return { token: _, value } = stmt {
            self.output.push_str(&self.indent());
            self.output.push_str("return");
            if let Some(expr) = value {
                self.output.push(' ');
                expr.accept(self);
            } else if self.in_synthesised_int_main {
                // `return;` inside a `void` main becomes `return 0;` in the generated `int main`.
                self.output.push_str(" 0");
            }
            self.output.push_str(";");
            self.output.push('\n');
        }
    }

    fn visit_break(&mut self, stmt: &Stmt) {
        if let Stmt::Break { token: _ } = stmt {
            self.writeln("break;");
        }
    }

    fn visit_continue(&mut self, stmt: &Stmt) {
        if let Stmt::Continue { token: _ } = stmt {
            self.writeln("continue;");
        }
    }

    fn visit_variable(&mut self, stmt: &Stmt) {
        if let Stmt::Variable { name, initialiser, type_, modifiers: _, derived: _ } = stmt {
            let cpp_type = self.translate_type(type_);
            self.output.push_str(&self.indent());
            self.output.push_str(&cpp_type);
            self.output.push(' ');
            self.output.push_str(&name.lexeme);
            if let Some(init) = initialiser {
                self.output.push_str(" = ");
                init.accept(self);
            }
            self.output.push_str(";");
            self.output.push('\n');
        }
    }

    fn visit_function(&mut self, stmt: &Stmt) {
        if let Stmt::Function { name, params, body, return_type, modifiers, generics: _ } = stmt {
            if modifiers.contains(&Modifier::Extern) {
                if self.builtin_function(name, params, return_type) {
                    return;
                }
            }
            
            // C++ requires `main` to return `int`. Cardamom allows `fn main()` (i.e. a
            // `void` return), so synthesise the `int` return type and the trailing
            // `return 0;` for that case.
            let is_main = name.lexeme == "main";
            let void_main = is_main && return_type.kind == TypeKind::Void;
            let ret_type = if void_main {
                "int".to_string()
            } else {
                self.translate_type(return_type)
            };
            let param_str = self.translate_params(params);

            self.writeln(&format!("{} {}({})", ret_type, name.lexeme, param_str));
            self.output.push_str(&self.indent());
            self.output.push_str("{\n");
            self.indent_level += 1;

            let old_in_main = self.in_synthesised_int_main;
            self.in_synthesised_int_main = void_main;
            for s in body {
                s.accept(self);
            }
            if void_main {
                self.writeln("return 0;");
            }
            self.in_synthesised_int_main = old_in_main;

            self.indent_level -= 1;
            self.writeln("}");
        }
    }

    fn visit_import(&mut self, stmt: &Stmt) {
        if let Stmt::Import { path, alias: _ } = stmt {
            self.output.push_str(&self.indent());
            self.output.push_str("#include ");
            path.accept(self);
            self.output.push('\n');
        }
    }

    fn visit_class(&mut self, stmt: &Stmt) {
        if let Stmt::Class { name, generics: _, modifier: _, public_methods, private_methods, protected_methods, static_methods, public_fields, private_fields, protected_fields, static_fields } = stmt {
            // Generate a class definition.
            self.writeln(&format!("class {} {{", name.lexeme));
            self.indent_level += 1;
            self.writeln("public:");
            self.indent_level += 1;
            // Combine all field declarations.
            for field in public_fields.iter()
                .chain(private_fields.iter())
                .chain(protected_fields.iter())
                .chain(static_fields.iter())
            {
                if let Stmt::Variable { name: field_name, type_, .. } = &**field {
                    let cpp_type = self.translate_type(type_);
                    self.writeln(&format!("{} {};", cpp_type, field_name.lexeme));
                }
            }
            self.indent_level -= 1;
            self.writeln("};");
            // Generate methods as standalone functions.
            let mut all_methods = Vec::new();
            all_methods.extend(public_methods.iter());
            all_methods.extend(private_methods.iter());
            all_methods.extend(protected_methods.iter());
            all_methods.extend(static_methods.iter());
            for method in all_methods {
                if let Stmt::Function { name: method_name, params, body, return_type, .. } = &**method {
                    let ret_type = self.translate_type(return_type);
                    let mut param_str = String::new();
                    // For instance methods, include a reference to the object.
                    param_str.push_str(&format!("{}& self", name.lexeme));
                    if !params.is_empty() {
                        param_str.push_str(", ");
                    }
                    for (i, param) in params.iter().enumerate() {
                        if let Stmt::Variable { name: param_name, type_, .. } = &**param {
                            let cpp_type = self.translate_type(type_);
                            write!(&mut param_str, "{} {}", cpp_type, param_name.lexeme).unwrap();
                            if i < params.len() - 1 {
                                param_str.push_str(", ");
                            }
                        }
                    }
                    self.writeln(&format!("{} {}_{}({})", ret_type, name.lexeme, method_name.lexeme, param_str));
                    self.output.push_str(&self.indent());
                    self.output.push_str("{\n");
                    self.indent_level += 1;
                    for s in body {
                        s.accept(self);
                    }
                    self.indent_level -= 1;
                    self.writeln("}");
                }
            }
        }
    }

    // Expression visitors
    fn visit_binary(&mut self, expr: &Expr) {
        if let Expr::Binary { left, op, right } = expr {
            self.output.push('(');
            left.accept(self);
            self.output.push(' ');
            self.output.push_str(&op.lexeme);
            self.output.push(' ');
            right.accept(self);
            self.output.push(')');
        }
    }

    fn visit_unary(&mut self, expr: &Expr) {
        if let Expr::Unary { op, right } = expr {
            self.output.push_str(&op.lexeme);
            right.accept(self);
        }
    }

    fn visit_literal(&mut self, expr: &Expr) {
        if let Expr::Literal { value } = expr {
            self.output.push_str(&value.lexeme);
        }
    }

    fn visit_grouping(&mut self, expr: &Expr) {
        if let Expr::Grouping { expression } = expr {
            self.output.push('(');
            expression.accept(self);
            self.output.push(')');
        }
    }

    fn visit_variable_expr(&mut self, expr: &Expr) {
        if let Expr::Variable { name } = expr {
            self.output.push_str(&name.lexeme);
        }
    }

    fn visit_assignment(&mut self, expr: &Expr) {
        if let Expr::Assignment { name, value, op } = expr {
            self.output.push_str(&name.lexeme);
            self.output.push(' ');
            self.output.push_str(&op.lexeme);
            self.output.push(' ');
            value.accept(self);
        }
    }

    fn visit_call(&mut self, expr: &Expr) {
        if let Expr::Call { callee, paren: _, arguments } = expr {
            if let Expr::MemberAccess { object, name } = &**callee {
                self.visit_member_call(object, name, arguments);
                return;
            }

            callee.accept(self);
            self.output.push('(');
            self.write_call_arguments(arguments);
            self.output.push(')');
        }
    }

    fn visit_generic_call(&mut self, expr: &Expr) {
        if let Expr::GenericCall { callee, paren: _, arguments, generics: _ } = expr {
            // In C++ generics (templates) are handled differently; ignore generic arguments here.
            callee.accept(self);
            self.output.push('(');
            for (i, arg) in arguments.iter().enumerate() {
                arg.accept(self);
                if i < arguments.len() - 1 {
                    self.output.push_str(", ");
                }
            }
            self.output.push(')');
        }
    }

    fn visit_member_access(&mut self, expr: &Expr) {
        if let Expr::MemberAccess { object, name } = expr {
            object.accept(self);
            match *object.clone() {
                Expr::Reference { object: _ } => self.output.push_str("->"),
                Expr::MutReference { object: _ } => self.output.push_str("->"),
                _ => self.output.push_str("."),
            }
            self.output.push_str(&name.lexeme);
        }
    }

    fn visit_static_access(&mut self, expr: &Expr) {
        if let Expr::StaticAccess { object, name } = expr {
            object.accept(self);
            self.output.push_str("::");
            self.output.push_str(&name.lexeme);
        }
    }

    fn visit_index(&mut self, expr: &Expr) {
        if let Expr::Index { object, index, token: _ } = expr {
            object.accept(self);
            self.output.push('[');
            index.accept(self);
            self.output.push(']');
        }
    }

    fn visit_cast(&mut self, expr: &Expr) {
        if let Expr::Cast { object, type_ } = expr {
            self.output.push('(');
            self.output.push_str(&self.translate_type(type_));
            self.output.push_str(") ");
            object.accept(self);
        }
    }

    fn visit_class_init(&mut self, expr: &Expr) {
        if let Expr::ClassInit { name, arguments } = expr {
            // Map a class initialization to a call to its constructor.
            self.output.push_str(&name.lexeme);
            self.output.push_str("_init(");
            for (i, arg) in arguments.iter().enumerate() {
                arg.accept(self);
                if i < arguments.len() - 1 {
                    self.output.push_str(", ");
                }
            }
            self.output.push(')');
        }
    }

    fn visit_dereference(&mut self, expr: &Expr) {
        if let Expr::Dereference { object } = expr {
            self.output.push('*');
            object.accept(self);
        }
    }

    fn visit_reference(&mut self, expr: &Expr) {
        if let Expr::Reference { object } = expr {
            // `&T` is lowered to a by-value `T` (see `translate_type`), so there is nothing
            // to take the address of here.
            object.accept(self);
        }
    }

    fn visit_mut_reference(&mut self, expr: &Expr) {
        if let Expr::MutReference { object } = expr {
            self.output.push('&');
            object.accept(self);
        }
    }

    fn visit_closure(&mut self, expr: &Expr) {
        if let Expr::Closure { name: _, parameters, param_types, body, return_type } = expr {
            // A closure is an *expression*, so it has to be emitted inline. Emitting a
            // named function definition here produced C++ that could never compile;
            // a lambda is both valid in expression position and able to capture.
            //
            // Parameter types are usually inferred from the closure's expected type, so
            // prefer the type checker's result and fall back to any explicit annotations.
            let inferred_params = match self.expr_types.get(&(expr as *const Expr)).map(|t| &t.kind) {
                Some(TypeKind::Function(params, _)) => Some(params.clone()),
                _ => None,
            };

            let mut params_str = String::new();
            for (i, param) in parameters.iter().enumerate() {
                let param_type = inferred_params
                    .as_ref()
                    .and_then(|params| params.get(i))
                    .or_else(|| param_types.get(i))
                    .map(|ty| self.translate_type(ty))
                    .unwrap_or_else(|| "auto".to_string());
                if i > 0 {
                    params_str.push_str(", ");
                }
                write!(&mut params_str, "{} {}", param_type, param.lexeme).unwrap();
            }

            let ret_type = self.translate_type(return_type);
            // Capture by value so the lambda stays valid after the enclosing scope ends
            // (closures can be returned from functions).
            self.output.push_str(&format!("[=]({}) -> {} ", params_str, ret_type));

            let body_code = self.capture_output(|gen| {
                match &**body {
                    Stmt::Block { .. } => body.accept(gen),
                    _ => {
                        gen.writeln("{");
                        gen.indent_level += 1;
                        body.accept(gen);
                        gen.indent_level -= 1;
                        gen.writeln("}");
                    }
                }
            });
            // The body was rendered as statements, so drop the leading indent and the
            // trailing newline to keep it inside the surrounding expression.
            self.output.push_str(body_code.trim_start());
            while self.output.ends_with('\n') {
                self.output.pop();
            }
        }
    }

    fn visit_array(&mut self, expr: &Expr) {
        // For arrays, generate an initializer list for std::vector.
        if let Expr::Array { elements } = expr {
            self.output.push('{');
            for (i, element) in elements.iter().enumerate() {
                element.accept(self);
                if i < elements.len() - 1 {
                    self.output.push_str(", ");
                }
            }
            self.output.push('}');
        }
    }

    fn visit_tuple(&mut self, expr: &Expr) {
        if let Expr::Tuple { elements } = expr {
            // Represent a tuple as a comma-separated list enclosed in parentheses.
            self.output.push('(');
            for (i, element) in elements.iter().enumerate() {
                element.accept(self);
                if i < elements.len() - 1 {
                    self.output.push_str(", ");
                }
            }
            self.output.push(')');
        }
    }

    fn visit_member_assignment(&mut self, expr: &Expr) {
        if let Expr::MemberAssignment { object, name, value, op } = expr {
            object.accept(self);
            match *object.clone() {
                Expr::Reference { object: _ } | Expr::MutReference { object: _ } => {
                    self.output.push_str("->")
                }
                _ => self.output.push('.'),
            }
            self.output.push_str(&name.lexeme);
            self.output.push(' ');
            self.output.push_str(&op.lexeme);
            self.output.push(' ');
            value.accept(self);
        }
    }

    fn visit_static_assignment(&mut self, expr: &Expr) {
        if let Expr::StaticAssignment { object, name, value, op } = expr {
            object.accept(self);
            self.output.push_str("::");
            self.output.push_str(&name.lexeme);
            self.output.push(' ');
            self.output.push_str(&op.lexeme);
            self.output.push(' ');
            value.accept(self);
        }
    }

    fn visit_index_assignment(&mut self, expr: &Expr) {
        if let Expr::IndexAssignment { object, index, value, op, token: _ } = expr {
            object.accept(self);
            self.output.push('[');
            index.accept(self);
            self.output.push(']');
            self.output.push(' ');
            self.output.push_str(&op.lexeme);
            self.output.push(' ');
            value.accept(self);
        }
    }

    fn visit_ptr_assignment(&mut self, expr: &Expr) {
        // Handle pointer assignment similarly to a normal assignment but with dereference.
        if let Expr::PtrAssignment { object, value, op } = expr {
            self.output.push('*');
            object.accept(self);
            self.output.push(' ');
            self.output.push_str(&op.lexeme);
            self.output.push(' ');
            value.accept(self);
        }
    }

    fn visit_extension(&mut self, stmt: &Stmt) {
        if let Stmt::Extension { target, methods } = stmt {
            let target_name = target.name.lexeme.clone();
            for method in methods {
                if let Stmt::Function { name, params, return_type, body, .. } = &**method {
                    let ret_type = self.translate_type(return_type);
                    let mut param_str = String::new();
                    // For extension methods, add the extended type as the first parameter.
                    write!(&mut param_str, "{}& self", self.translate_type(target)).unwrap();
                    if !params.is_empty() {
                        param_str.push_str(", ");
                    }
                    for (i, param) in params.iter().enumerate() {
                        if let Stmt::Variable { name: param_name, type_, .. } = &**param {
                            let t = self.translate_type(type_);
                            write!(&mut param_str, "{} {}", t, param_name.lexeme).unwrap();
                            if i < params.len() - 1 {
                                param_str.push_str(", ");
                            }
                        }
                    }
                    // Generate the function prototype (and body, if desired).
                    self.writeln(&format!("{} {}_extension_{}({})", ret_type, target_name, name.lexeme, param_str));
                    // Optionally, generate a stub body:
                    self.writeln("{");
                    self.indent_level += 1;
                    for s in body {
                        s.accept(self);
                    }
                    self.indent_level -= 1;
                    self.writeln("}");
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lexer::Lexer;
    use crate::parser::Parser;
    use crate::typecheck::TypeChecker;
    use crate::utils::symtable::SymbolTable;
    use std::io::Write;
    use std::process::{Command, Stdio};

    fn parse_and_check_with_types(relative_path: &str) -> (Module, ExprTypes) {
        let filename = format!("{}/{}", env!("CARGO_MANIFEST_DIR"), relative_path);
        let source = std::fs::read_to_string(&filename).expect("fixture should be readable");

        let mut lexer = Lexer::new(source.clone(), filename.clone());
        lexer.scan_tokens();
        assert!(!lexer.had_error, "`{}` should lex cleanly", relative_path);

        let mut parser = Parser::new(lexer.tokens.clone(), source.clone(), filename.clone());
        let module = parser
            .parse()
            .unwrap_or_else(|err| panic!("`{}` should parse: {}", relative_path, err.to_string()));
        assert!(!parser.had_error, "`{}` should parse cleanly", relative_path);

        let mut symtable = SymbolTable::new();
        let mut checker = TypeChecker::new(&mut symtable, filename, source);
        checker.check_module(&module);
        assert_eq!(checker.error_count(), 0, "`{}` should typecheck", relative_path);

        let expr_types = checker.expr_types.clone();
        (module, expr_types)
    }

    /// Every fixture in `tests/pass` must lower to C++ that actually compiles.
    #[test]
    fn pass_fixtures_generate_compilable_cpp() {
        let fixtures = std::fs::read_dir(format!("{}/tests/pass", env!("CARGO_MANIFEST_DIR")))
            .expect("tests/pass should be readable");

        for entry in fixtures {
            let path = entry.expect("directory entry should be readable").path();
            if path.extension().and_then(|e| e.to_str()) != Some("crdm") {
                continue;
            }
            let relative = format!("tests/pass/{}", path.file_name().unwrap().to_string_lossy());

            let (module, expr_types) = parse_and_check_with_types(&relative);
            let mut generator = CppCodeGenerator::with_types(expr_types);
            let code = generator.generate(&module);

            let stem = path.file_stem().unwrap().to_string_lossy().to_string();
            let cpp_path = format!("/tmp/cardamom_pass_{}_{}.cpp", std::process::id(), stem);
            let bin_path = format!("/tmp/cardamom_pass_{}_{}", std::process::id(), stem);
            std::fs::write(&cpp_path, code).expect("generated C++ should be writable");

            let compile = Command::new("g++")
                .arg(&cpp_path)
                .arg("-I")
                .arg(env!("CARGO_MANIFEST_DIR"))
                .arg("-o")
                .arg(&bin_path)
                .output()
                .expect("g++ should run");

            assert!(
                compile.status.success(),
                "`{}` should generate compilable C++:\n{}",
                relative,
                String::from_utf8_lossy(&compile.stderr)
            );

            let _ = std::fs::remove_file(cpp_path);
            let _ = std::fs::remove_file(bin_path);
        }
    }

    fn parse_and_check(relative_path: &str) -> Module {
        let filename = format!("{}/{}", env!("CARGO_MANIFEST_DIR"), relative_path);
        let source = std::fs::read_to_string(&filename).expect("fixture should be readable");

        let mut lexer = Lexer::new(source.clone(), filename.clone());
        lexer.scan_tokens();
        assert!(!lexer.had_error, "`{}` should lex cleanly", relative_path);

        let mut parser = Parser::new(lexer.tokens.clone(), source.clone(), filename.clone());
        let module = match parser.parse() {
            Ok(module) => module,
            Err(err) => panic!("`{}` should parse: {}", relative_path, err.to_string()),
        };
        assert!(!parser.had_error, "`{}` should parse cleanly", relative_path);

        let mut symtable = SymbolTable::new();
        let checker_source = std::fs::read_to_string(&filename).expect("fixture should be readable");
        let mut checker = TypeChecker::new(&mut symtable, filename, checker_source);
        checker.check_module(&module);
        assert_eq!(checker.error_count(), 0, "`{}` should typecheck", relative_path);

        module
    }

    #[test]
    fn bf_codegen_compiles_and_runs_input_echo() {
        let module = parse_and_check("bf.crdm");
        let mut generator = CppCodeGenerator::new();
        let code = generator.generate(&module);

        let pid = std::process::id();
        let cpp_path = format!("/tmp/cardamom_bf_{}.cpp", pid);
        let bin_path = format!("/tmp/cardamom_bf_{}", pid);
        std::fs::write(&cpp_path, code).expect("generated C++ should be writable");

        let compile = Command::new("g++")
            .arg(&cpp_path)
            .arg("-I")
            .arg(env!("CARGO_MANIFEST_DIR"))
            .arg("-o")
            .arg(&bin_path)
            .output()
            .expect("g++ should run");
        assert!(
            compile.status.success(),
            "generated bf C++ should compile:\n{}",
            String::from_utf8_lossy(&compile.stderr)
        );

        let mut child = Command::new(&bin_path)
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .spawn()
            .expect("generated bf binary should run");
        child
            .stdin
            .as_mut()
            .expect("stdin should be open")
            .write_all(b",.\nA\n")
            .expect("stdin write should succeed");
        let output = child.wait_with_output().expect("run should finish");
        assert!(output.status.success(), "generated bf binary should exit cleanly");

        let stdout = String::from_utf8_lossy(&output.stdout);
        assert!(
            stdout.ends_with("A\n"),
            "generated bf binary should echo one input byte, got `{}`",
            stdout
        );

        let _ = std::fs::remove_file(cpp_path);
        let _ = std::fs::remove_file(bin_path);
    }
}
